export const SWAGGER_CONSTANTS = {
    SET_VALUE: 'HODFORDS:SWAGGER:SET_VALUE',
    PUBLIC_API: 'HODFORDS:SWAGGER:PUBLIC_API',
    PERMISSIONS: 'HODFORDS:SWAGGER:PERMISSIONS'
};

export const SWAGGER_OPTIONS = 'SWAGGER_OPTIONS';
